markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-spaceship
  - jekyll-mermaid

# GitHub Pages configuration
title: "Sthefany Ricardo - QA Engineer"
description: "Profissional da área de Garantia da Qualidade de Software e Automação de Testes"
url: "https://sthefanyricardo.github.io"
baseurl: "/sthefanyricardo"

# Theme and layout
remote_theme: pages-themes/cayman@v0.2.0

# Custom theme colors
theme_color: "#6567a5"
primary_color: "#6567a5"

# Enable Mermaid via JavaScript
mermaid: true
